
DROP TABLE STOCK;
DROP TABLE BUY;
DROP TABLE STORE_ORDER;
DROP TABLE PAY;
DROP TABLE PRODUCT;

DROP SEQUENCE SEQ_PAY;
DROP SEQUENCE SEQ_BUY;
DROP SEQUENCE ORDER_SEQ;

CREATE TABLE PAY(
    PAY_ID NUMBER(8) PRIMARY KEY,
    PAY_DATE DATE NOT NULL,
    PAY_TIME VARCHAR2(50) NOT NULL,
    PAY_TYPE VARCHAR2(50),
    FINAL_AMOUNT NUMBER(8)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(8) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER(8) NOT NULL 
) ;
CREATE TABLE BUY(
    BUY_NUM NUMBER(8) PRIMARY KEY,
    PAY_ID NUMBER(8),
    PRODUCT_ID NUMBER(8) NOT NULL,
    PRODUCT_PRICE NUMBER(8) NOT NULL,
    BUY_QUANTITY NUMBER(8) NOT NULL,
    BUY_PRICE  NUMBER(8) NOT NULL,
    foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID),
    foreign key(PAY_ID) references PAY(PAY_ID)
);


CREATE TABLE STOCK(
     PRODUCT_ID NUMBER(8) PRIMARY KEY,
     PRODUCT_QUANTITY NUMBER(8) NOT NULL,
     foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID)
);




CREATE TABLE STORE_ORDER(
     OEDER_SEQ NUMBER(8) PRIMARY KEY,
     PRODUCT_ID NUMBER(8) NOT NULL,
     ORDER_QUANTITY NUMBER(8) NOT NULL,
     ORDER_DATE DATE NOT NULL,
     foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE SEQ_PAY;
CREATE SEQUENCE SEQ_BUY;
CREATE SEQUENCE ORDER_SEQ;


----물품 목록 초기 세팅----
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('1', '새우깡', '1500');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('2', '토레타', '2000');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('3', '연세우유빵', '3000');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('4', '황치즈쿠키', '2700');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('5', '하리보', '2000');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('6', '참이슬', '1000');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('7', '테라', '1500');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('8', '바나나', '5000');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('9', '허쉬타르트', '1500');
INSERT INTO "HR"."PRODUCT" (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES ('10', '바나나우유', '1800');


----물품 수량 초기 세팅----
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('1', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('2', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('3', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('4', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('5', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('6', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('7', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('8', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('9', '10');
INSERT INTO "HR"."STOCK" (PRODUCT_ID, PRODUCT_QUANTITY) VALUES ('10', '10');